version: '3.8'

services:
  flask_app:
    build: .
    container_name: sentinel_backend
    ports:
      - "5000:5000"
    restart: always
    environment:
      - REDIS_HOST=redis-db
    depends_on:
      - redis-db
    networks:
      - sentinel-net

  redis-db:
    image: redis:alpine
    container_name: sentinel_redis
    networks:
      - sentinel-net

  nginx_proxy:
    image: nginx:alpine
    container_name: sentinel_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - flask_app
    networks:
      - sentinel-net

  prometheus:
    image: prom/prometheus
    container_name: sentinel_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
    networks:
      - sentinel-net

  grafana:
    image: grafana/grafana
    container_name: sentinel_grafana
    ports:
      - "3000:3000"
    restart: always
    networks:
      - sentinel-net

  node_exporter:
    image: prom/node-exporter
    container_name: sentinel_node_exporter
    restart: always
    networks:
      - sentinel-net

  # --- AB YAHAN SE NAYA DATABASE SETUP ADD KARO ---

  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_database
    networks:
      - sentinel-net

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://user:password@postgres:5432/my_database?sslmode=disable"
    depends_on:
      - postgres
    networks:
      - sentinel-net

  mongodb:
    image: mongo:latest
    container_name: mongodb_db
    networks:
      - sentinel-net

  mongodb-exporter:
    image: percona/mongodb_exporter:0.40
    container_name: mongodb_exporter
    command: ["--mongodb.uri=mongodb://mongodb:27017"]
    depends_on:
      - mongodb
    networks:
      - sentinel-net

networks:
  sentinel-net:
    driver: bridge
