version: '3.8'

services:
  flask_app:
    build: .
    container_name: sentinel_backend
    restart: always
    environment:
      - REDIS_HOST=redis-db
    depends_on:
      - redis-db
    networks:
      - sentinel-net

  redis-db:
    image: redis:alpine
    container_name: sentinel_redis
    networks:
      - sentinel-net

  nginx_proxy:
    image: nginx:alpine
    container_name: sentinel_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - flask_app
    networks:
      - sentinel-net

  prometheus:
    image: prom/prometheus
    container_name: sentinel_prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
    networks:
      - sentinel-net

  grafana:
    image: grafana/grafana
    container_name: sentinel_grafana
    ports:
      - "3000:3000"
    restart: always
    networks:
      - sentinel-net

  node_exporter:
    image: prom/node-exporter
    container_name: sentinel_node_exporter
    restart: always
    networks:
      - sentinel-net

networks:
  sentinel-net:
    driver: bridge
